# Generated by Django 6.1 on 2026-09-28 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_certifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
